<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE internationalization [
	<!ELEMENT text (#PCDATA)>
	<!ATTLIST text key ID #REQUIRED>
]>

<Internationalization langCode="en">

	<text key="headerPresenter_languageNameAbbreviation">
		En
	</text>
	<text key="header_learnMore">
		Learn more about ESASky!
	</text>
	<text key="header_getURLCurrentView">
		Get URL for the current view
	</text>
	<text key="header_viewInWWTAbbr">
		View in WWT
	</text>
	<text key="header_viewInWWTFull">
		View in WorldWide Telescope
	</text>
	<text key="header_takeScreenshotFull">
		Take a screenshot of the current screen
	</text>
	<text key="header_takeScreenshot">
		Screenshot
	</text>
	<!-- menuPanel -->
	<text key="header_videoTutorials">
		Video Tutorials
	</text>
	<text key="header_comunity">
		Feedback
	</text>
	<text key="header_aboutUs">
		About Us
	</text>
	<text key="header_releaseNotes">
		Release Notes
	</text>
	<text key="header_newsletter">
		Newsletter
	</text>
	<text key="header_sciMode">
		Sci. Mode
	</text>
	<text key="header_sciModeSwitchTooltip">
		Switch between science and explorer mode
	</text>
	<text key="header_share">
		Share
	</text>
	<text key="header_help">
		Help
	</text>
	<text key="header_gridFull">
		Toggle showing coordinate grid on top of the sky
	</text>
	<text key="header_gridDropdown">
		Coordinate grid
	</text>


	<!-- SSOOrbitMetadataCallback -->
	<text key="SSOOrbitMetadataCallback_retrievingOrbitPoints">
		Retrieving $SSONAME$ orbit&#39;s points
	</text>

	<!-- countRequestCallback -->
	<text key="CountRequestCallback_countingAvailableData">
		Counting Available Data
	</text>

	<!-- publicationsSourcesCallback -->
	<text key="PublicationsSourcesCallback_retrievingPubSources">
		Retrieving sources with publications
	</text>

	<!-- publicationsBySourceCallback -->
	<text key="PublicationsBySourceCallback_retrievingPubsOf">
		Retrieving publications of $NAME$
	</text>
	<text key="PublicationsBySourceCallback_helpTitle">
		Publications
	</text>
	<text key="resultsPresenter_helpDescription_publications_ADS-PUB">
		Publications associated to this source in SIMBAD plus
		access to sources for each of the publications.
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-interface#publications"
		target="_blank"&gt;
		Full documentation of this feature.
		&lt;/a&gt; </text>

	<!-- metadataCallback -->
	<text key="tabulator_retrievingMissionData">
		Retrieving $NAME$ data
	</text>
	<text key="MetadataCallback_retrievingSSOMetadata">
		Retrieving SSO $NAME$ metadata
	</text>

	<!-- searchPanel -->
	<text key="searchPanel_inputByTargetName">
		Input examples by target name:
	</text>
	<text key="searchPanel_solarSystemObjects">
		Solar System objects:
	</text>
	<text key="searchPanel_inputByName">
		By name:
	</text>
	<text key="searchPanel_inputByObjectNumber">
		By object number:
	</text>
	<text key="searchPanel_inputByCoordinates">
		Input examples by coordinates:
	</text>
	<text key="searchPanel_wrongCoordsInput">
		Error parsing coordinates. Please review the allowed
		input formats.
	</text>
	<text key="searchPanel_targetNotFound">
		Not found
	</text>
	<text key="searchPanel_ssoTargetNotFound">
		Solar System Object not found.
	</text>
	<text key="searchPanel_seeMoreExamples">
		See more examples
	</text>
	<text key="searchPanel_search">
		Search...
	</text>

	<!-- searchPresenter_resolvingTarget -->
	<text key="searchPresenter_resolvingTarget">
		Resolving $NAME$...
	</text>

	<!-- uploadTargetList -->
	<text key="uploadTargetList_targetList">
		Target list file:
	</text>
	<text key="uploadTargetList_targetListDescriptionText">
		Select an example target list or select a text file
		containing your list of targets, either names resolved by SIMBAD or a
		list of coordinates.
		While the list is loading, the message 'Resolving target list...' appears
		at the top of the interface, then once loaded, the target list appears
		on the left.
		&lt;br&gt;&lt;br&gt;
		Click on a target to view it in the
		sky.
		If an object has not been resolved by SIMBAD it will be crossed out.
		Below the target list are some video style buttons, press play to play
		through the list of targets, the target being displayed will be
		highlighted in dark grey in the list.
		Text and comments can also be
		added to a target list and the text is displayed in ESASky below the
		player buttons.
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-target-lists"
		target="_blank"&gt;
		See here for the format needed to display text and some example files.
		&lt;/a&gt;
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-interface#list"
		target="_blank"&gt;
		Full documentation of this feature.
		&lt;/a&gt; </text>
	<text key="uploadTargetList_uploadTargetList">
		Upload Target List
	</text>
	<text key="uploadTargetList_uploadTargetListFailed">
		failed due to
	</text>
	<text key="uploadTargetList_removeTargetList">
		Remove target list
	</text>
	<text key="uploadTargetList_title">
		Target List
	</text>
	<text key="uploadTargetList_selectList">
		Select Target List
	</text>
	<text key="uploadTargetList_orUpload">
		or
	</text>
	<text key="uploadTargetList_resolvingTargetList">
		Resolving target list
	</text>

	<!-- uploadTargetListPanel -->
	<text key="uploadTargetListPanel_MultiTargetCatalog">
		Multi Target Catalog
	</text>

	<!-- treeMap -->
	<text key="treeMap_ASTRO_IMAGING">
		Image Observations
	</text>
	<text key="treeMap_ASTRO_CATALOGUE">
		Catalogues
	</text>
	<text key="treeMap_SSO">
		Solar System Object Observations
	</text>
	<text key="treeMap_loading_ASTRO_IMAGING">
		Loading Observations
	</text>
	<text key="treeMap_loading_ASTRO_CATALOGUE">
		Loading Catalogues
	</text>
	<text key="treeMap_loading_SSO">
		Loading Solar System Objects
	</text>
	<text key="treeMap_noData_ASTRO_IMAGING">
		No Image Observations Found
	</text>
	<text key="treeMap_noData_ASTRO_CATALOGUE">
		No Catalogue Entries Found
	</text>
	<text key="treeMap_noData_SSO">
		No SSO Observations Found
	</text>
	<text key="treeMap_nameOfSelectedLabel">
		SSO: $SSONAME$ ($SSOTYPE$)
	</text>
	<text key="treeMap_notInRange_ASTRO_IMAGING">
		No Image data found in this wavelength range.
	</text>
	<text key="treeMap_notInRange_ASTRO_CATALOGUE">
		No Catalogue entries found in this wavelength range.
	</text>
	<text key="treeMap_notInRange_SSO">
		No SSO Observations found in this wavelength range.
	</text>

	<!-- Sky -->
	<text key="sky_wavelength">
		Wavelength
	</text>
	<text key="sky_selectWavelength">
		Select wavelength
	</text>
	<text key="sky_skies">
		Skies
	</text>
	<text key="sky_selectSky">
		Select Sky
	</text>
	<text key="sky_selectSky_help">
		The skies are ordered into wavelength regions, from
		Gamma-ray to Radio, and an Others section at the bottom which
		currently holds physical models.
		Select a sky by choosing the wavelength region in the first panel, and
		browse the skies in the second panel.
		Details on each sky can be found by clicking the i icon. For further details
		and a list of all the available skies, go to the skies (HiPS)
		information page.
		&lt;br&gt;&lt;br&gt;
		The colour of the skies can be
		modified with the colour map options 'Native', 'EOSB', 'Planck',
		'Rainbow', 'Greyscale' and 'Cubehelix'.
		&lt;br&gt;&lt;br&gt;
		A sky can
		be added to the stack by selecting the + button.
		&lt;br&gt;&lt;br&gt;
		Click on the video style buttons to play through the skies in the
		stack, skip forward, backwards or stop.
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-interface#skies"
		target="_blank"&gt;
		Full documentation of this feature.
		&lt;/a&gt; </text>
	<text key="sky_selectASky">
		Select a sky
	</text>
	<text key="sky_skyDetails">
		Sky details
	</text>
	<text key="sky_removeSky">
		Remove sky
	</text>
	<text key="sky_loadingSkies">
		Loading skies
	</text>

	<!-- HiPS Details Popup -->
	<text key="hiPSDetailsPopup_mapName">
		Map name:
	</text>
	<text key="hiPSDetailsPopup_mission">
		Mission:
	</text>
	<text key="hiPSDetailsPopup_instrument">
		Instrument:
	</text>
	<text key="hiPSDetailsPopup_wavFreq">
		Wavelength/frequency:
	</text>
	<text key="hiPSDetailsPopup_mapCreatedBy">
		Map created by
	</text>
	<text key="hiPSDetailsPopup_forMoreInformation">
		For more information click&amp;nbsp;
	</text>
	<text key="hiPSDetailsPopup_here">
		here
	</text>
	<text key="hiPSDetailsPopup_close">
		Close
	</text>

	<!-- Change Palette Button -->
	<text key="changePaletteBtn_changePaletteTooltip">
		Colour palette
	</text>

	<text key="dateFilter_resetFilter">
		Reset filter
	</text>
	<text key="rangeFilter_resetFilter">
		Reset filter
	</text>

	<!-- commonObservationTablePanel -->
	<text key="tabulator_sendRowToVOA">
		Send row to Virtual Observatory application
	</text>

	<!-- planObservationPanel -->
	<text key="planObservationPanel_projectFutureObservations">
		Observations Planning Tool
	</text>
	<text key="planObservationPanel_helpMessageText">
		This tool projects onto the sky the footprints of astronomical instruments,
		at any chosen position and orientation, and has been developed to aid professional
		astronomers when they are defining their future observation proposals for a particular
		space mission or ground-based telescope. Currently the tool works for all the
		James Webb Space Telescope (JWST) instruments (including being able to project the full
		focal plane of the JWST), and for the XMM-Newton EPIC-pn camera.
		&lt;br&gt;&lt;br&gt;
		IMPORTANT: This functionality is not intended to
		replace the JWST ATP tool, but just to provide a quick-look aid for
		astronomers planning JWST observations that require overlapping with
		existing observations by other missions available in ESASky, or who
		want to make sure that their instrument or parallel pointings are
		covering/avoiding particular features or objects in their target
		regions.
		The coordinates and positional angles of the pointings defined using this
		functionality have to be checked and refined in the APT, which is the
		official tool for preparing JWST observations.
		For information and installation of the APT, go to
		&lt;a href="//www.stsci.edu/hst/proposing/apt" target="_blank"&gt;
		this STSci webpage&lt;/a&gt;; for details on the different JWST
		instruments,
		&lt;a href="//stsci.edu/jwst/instrumentation" target="_blank"&gt;
		click here.&lt;/a&gt;
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.youtube.com/watch?v=n2iW1HfVgVE&amp;feature=youtu.be"
		target="_blank"&gt;
		See also the following video: How to plan future JWST observations&lt;/a&gt;
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-interface#planning"
		target="_blank"&gt;
		Full documentation of this feature.&lt;/a&gt; </text>
	<!-- futureFootprintRow -->
	<text key="futureFootprintRow_addJWSTInstrument">
		Add a JWST instrument
	</text>
	<text key="futureFootprintRow_rotation">
		Rotation
	</text>
	<text key="futureFootprintRow_instrAngleInfo_JWST">
		For more information click &lt;a href="//jwst-docs.stsci.edu/jwst-observatory-characteristics/jwst-position-angles-ranges-and-offsets" target="_blank"&gt;here&lt;/a&gt;
	</text>
	<text key="futureFootprintRow_instrAngleInfo_XMM">
		For more information click &lt;a href="//xmm-tools.cosmos.esa.int/external/xmm_user_support/documentation/uhb/posdet.html" target="_blank"&gt;here&lt;/a&gt;
	</text>
	<text key="futureFootprintRow_instrAngle">
		Angle of the instrument on the focal plane:
	</text>
	<text key="futureFootprintRow_offsetAngle">
		Offset Angle:
	</text>
	<text key="futureFootprintRow_totalRotation">
		Rotation of the focal plane on the sky:
	</text>
	<text key="futureFootprintRow_tooltip">
		$MISSION$ Angle Details
	</text>
	<text key="futureFootprintRow_allInstruments">
		All Instruments
	</text>
	<text key="futureFootprintRow_removeFootprint">
		Remove this footprint
	</text>
	<text key="futureFootprintRow_increase">
		Increase
	</text>
	<text key="futureFootprintRow_angleBy">
		angle by
	</text>
	<text key="futureFootprintRow_decrease">
		Decrease
	</text>
	<text key="futureFootprintRow_copyCoordinatesAndData">
		Copy coordinates and data
	</text>
	<text key="futureFootprintRow_centre">
		Centre
	</text>
	<text key="futureFootprintRow_coordinateSystem">
		Coordinate system:
	</text>
	<text key="futureFootprintRow_dataCopiedToClipboard">
		Data copied to clipboard
	</text>
	<text key="futureFootprintRow_aperture">
		Aperture
	</text>


	<!-- screenShotDialogBox -->
	<text key="screenShotDialogBox_screenshot">
		ESASky Screenshot
	</text>

	<!-- ctrlToolBar -->
	<text key="ctrlToolBar_URLClipboard">
		URL copied to clipboard
	</text>

	<!-- ctrlToolBarPresenter -->
	<text key="ctrlToolBarPresenter_bibcode">
		Bibcode: $HTML$
	</text>
	<text key="ctrlToolBarPresenter_authors">
		Authors: $HTML$
	</text>
	<text key="ctrlToolBarPresenter_journal">
		Journal: $JOURNAL$, $DATE$
	</text>
	<text key="ctrlToolBarPresenter_pubSources">
		Publication&#39;s sources:
	</text>
	<text key="ctrlToolBarPresenter_adsSearch">
		ADS Search: $HTML$
	</text>
	<text key="ctrlToolBarPresenter_authorSources">
		Author&#39;s related sources:
	</text>
	<text key="ctrlToolBarPresenter_showingMaxSources">
		Showing only the first $COUNT$ sources
	</text>
	<text key="ctrlToolBarPresenter_showingCountSources">
		Showing $COUNT$ sources
	</text>
	<text key="ctrlToolBarPresenter_loadPublicationDetails">
		Loading Publication Details
	</text>
	<text key="ctrlToolBarPresenter_retrievingPublicationTargetList">
		Retrieving Target List
	</text>
	<text key="ctrlToolBarPresenter_loadingAuthorSources">
		Searching for sources in $AUTHOR$ publications
	</text>

	<!-- playerPanel -->
	<text key="playerPanel_next">
		Next
	</text>
	<text key="playerPanel_pause">
		Pause
	</text>
	<text key="playerPanel_play">
		Play
	</text>
	<text key="playerPanel_previous">
		Previous
	</text>
	<text key="playerPanel_surveyTourStarted">
		Survey tour started
	</text>

	<!-- sampConstants -->
	<text key="sampConstants_help">
		Help on Interoperability Information (SAMP)
	</text>
	<text key="sampConstants_sendingViaSamp">
		Sending @@ via SAMP
	</text>

	<!-- webConstants -->
	<text key="webConstants_manageSkies">
		Manage skies
	</text>
	<text key="webConstants_uploadTargetList">
		Manage List of Targets
	</text>
	<text key="webConstants_exploreImageObservations">
		Explore image observations for this region
	</text>
	<text key="webConstants_exploreCatalogue">
		Explore catalogue data for this region
	</text>
	<text key="webConstants_exploreData">
		Explore data for $TARGET$
	</text>
	<text key="webConstants_trackSSO">
		Track solar system objects through the search box
	</text>
	<text key="webConstants_projectFutureObservations">
		Observations Planning Tool
	</text>
	<text key="webConstants_explorePublications">
		Explore publications data for this region
	</text>
	<text key="webConstants_exploreRandomTarget">
		Explore a random target
	</text>

	<!-- displayUtils -->
	<text key="displayUtils_connectivityProblems">
		Connectivity problem
	</text>
	<text key="displayUtils_VOnotFound">
		We could not find any Virtual Observatory (VO)
		compatible tool running
		on your computer
	</text>
	<text key="displayUtils_startOneOf">
		Please start one of
	</text>
	<text key="displayUtils_toCommunicateWithDS9">
		In order to communicate with DS9, you will also have to
		launch a
	</text>
	<text key="displayUtils_seeHelp">
		please see help for further details
	</text>
	<text key="displayUtils_tryAgain">
		Once any of these applications are running please try
		again.
	</text>

	<!-- resultsPresenter -->
	<text key="resultsPresenter_computingDataCrossMatch">
		Computing data cross-match for $SSOTEXT$
	</text>

	<text key="resultsPresenter_helpDescription_observations_INTEGRAL">
		INTEGRAL/IBIS observations consist on a large number of individual
		exposures (science windows) around a target position. For this reason
		and because of the large size of the IBIS field-of-view, it is
		unpractical to display the geometric footprints of all these science
		windows. Instead, ESASky only displays the central pointing position
		of each IBIS observation, each of which is linked to the full list of
		science windows associated with it.
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-observations#INTEGRAL"
		target="_blank"&gt;
		More information
		&lt;/a&gt; </text>
	<text key="resultsPresenter_helpDescription_observations_XMM">
		The XMM-Newton observations include public high-level Processing
		Pipeline System
		(PPS) products present in the XMM-Newton Science
		Archive
		(&lt;a href="//nxsa.esac.esa.int/nxsa-web/#home"
		target="_blank"&gt;XSA&lt;/a&gt;).
		The data included are the combined high-level image products from the
		three cameras (EPIC
		PN, EPIC MOS1, and EPIC MOS2) in the 0.2-12 keV
		energy band. The selection
		criteria are based on the existence of a
		public EPIC high-level combined image. The
		mosaic sub-pointing products
		are excluded but the whole combined mosaic
		observations are included.

		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-observations#XMM-Newton-OBS"
		target="_blank"&gt;
		More information
		&lt;/a&gt; </text>
	<text key="resultsPresenter_helpDescription_observations_Chandra">
		The Chandra dataset includes all public observations
		(images and spectra), updated regularly, from the ACIS, LETG,
		HETG and HRC instruments, available in the Chandra Data Archive
		through Chaser
		(&lt;a href="//cda.harvard.edu/chaser/"
		target="_blank"&gt;cda.harvard.edu/chaser/&lt;/a&gt;).
		Detailed information on the Chandra mission and its products can be found at
		the website:
		&lt;a href="//cxc.harvard.edu/" target="_blank"&gt;
		cxc.harvard.edu/&lt;/a&gt;.
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-observations#Chandra-OBS"
		target="_blank"&gt;
		More information
		&lt;/a&gt; </text>
	<text key="resultsPresenter_helpDescription_observations_SUZAKU">
		The observations include all public imaging products
		present in the SUZAKU archive at DARTS.
		Detailed information on the SUZAKU mission and its products can be found at
		&lt;a href="//www.darts.isas.jaxa.jp/astro/suzaku/" target="_blank"&gt;
		www.darts.isas.jaxa.jp/astro/suzaku/&lt;/a&gt;.
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-observations#SUZAKU-OBS"
		target="_blank"&gt;
		More information
		&lt;/a&gt; </text>
	<text key="resultsPresenter_helpDescription_observations_XMM-OM-OPTICAL">
		The
		&lt;a href="//www.cosmos.esa.int/web/xmm-newton/technical-details-om"
		target="_blank"&gt;
		Optical Monitor
		&lt;/a&gt;
		(OM) data in ESASky are public observations with at least one OM
		high-level image pipeline product, where individual OM sky images per
		filter are combined and North-aligned.
		Included in ESASky are the following OM Sky Image file types: RSIMAG
		Default-mode (RSIMAG), Full-frame low resolution (LSIMAG), Full-frame
		high resolution (HSIMAG), and User Defined (USIMAG).
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-observations#OM-OBS"
		target="_blank"&gt;
		More information
		&lt;/a&gt; </text>
	<text key="resultsPresenter_helpDescription_observations_XMM-OM-UV">
		The
		&lt;a href="//www.cosmos.esa.int/web/xmm-newton/technical-details-om"
		target="_blank"&gt;
		Optical Monitor
		&lt;/a&gt;
		(OM) data in ESASky are public observations with at least one OM
		high-level image pipeline product, where individual OM sky images per
		filter are combined and North-aligned.
		Included in ESASky are the following OM Sky Image file types: RSIMAG
		Default-mode (RSIMAG), Full-frame low resolution (LSIMAG), Full-frame
		high resolution (HSIMAG), and User Defined (USIMAG).
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-observations#OM-OBS"
		target="_blank"&gt;
		More information
		&lt;/a&gt; </text>
	<text key="resultsPresenter_helpDescription_observations_HST-OPTICAL">
		The Hubble Space Telescope (HST) observational data
		provided by ESASky are science products from the two Hubble data
		collections:
		&lt;ul&gt;
		&lt;li&gt;
		&lt;span&gt;
		The standard HST archive
		collection
		&lt;/span&gt;
		&lt;/li&gt;
		&lt;li&gt;
		&lt;span&gt;
		The Hubble
		Legacy Archive (HLA) collection
		&lt;/span&gt;
		&lt;/li&gt;
		&lt;/ul&gt;
		ESASky applies a filter on the HST
		archival data to show firstly all HST composite images (associations),
		then to show any single images (HST singleton) that are not part of
		any association.

		&lt;br&gt;&lt;br&gt;
		&lt;a href="//www.cosmos.esa.int/web/esdc/esasky-observations#HST-OBS"
		target="_blank"&gt;
		More information
		&lt;/a&gt; </text>

	<text key="resultsPresenter_helpDescription_observations_HST-UV">
		The Hubble Space Telescope (HST) observational data
		provided by ESASky are science products from the two Hubble data
		collections:
		&lt;ul&gt;
		&lt;li&gt;
		&lt;span&gt;
		The standard HST archive
		collection
		&lt;/span&gt;
		&lt;/li&gt;
		&lt;li&gt;
		&lt;span&gt;
		The Hubble
		Legacy Archive (HLA) collection
		&lt;/span&gt;
		&lt;/li&gt;
		&lt;/ul&gt;
		ESASky applies a filter on the HST
		archival data to show firstly all HST composite images (associations),
		then to show any single images (HST singleton) that are not part of
		any association.

		&lt;br&gt;&lt;br&gt;
		&lt;a href="//www.cosmos.esa.int/web/esdc/esasky-observations#HST-OBS"
		target="_blank"&gt;
		More information
		&lt;/a&gt; </text>

	<text key="resultsPresenter_helpDescription_observations_HST-IR">
		The Hubble Space Telescope (HST) observational data
		provided by ESASky are science products from the two Hubble data
		collections:
		&lt;ul&gt;
		&lt;li&gt;
		&lt;span&gt;
		The standard HST archive
		collection
		&lt;/span&gt;
		&lt;/li&gt;
		&lt;li&gt;
		&lt;span&gt;
		The Hubble
		Legacy Archive (HLA) collection
		&lt;/span&gt;
		&lt;/li&gt;
		&lt;/ul&gt;
		ESASky applies a filter on the HST
		archival data to show firstly all HST composite images (associations),
		then to show any single images (HST singleton) that are not part of
		any association.

		&lt;br&gt;&lt;br&gt;
		&lt;a href="//www.cosmos.esa.int/web/esdc/esasky-observations#HST-OBS"
		target="_blank"&gt;
		More information
		&lt;/a&gt; </text>

		<text key="resultsPresenter_helpDescription_observations_JWST_Near-IR">
		The James Webb Space Telescope (JWST) is the largest optical or infrared observatory ever launched to space.
		Developed in a collaboration between NASA, ESA, and CSA, Webb observes the Universe in infrared light from its orbit at the Lagrangian point L2, 1.5 million km away from Earth.
		&lt;br&gt;&lt;br&gt;
		Following launch, and after an initial commissioning phase of 6 months, the observatory has entered its regular science operations phase,
		during which approved observation programs will be performed. Scientific data is collected from a set of observer-created programs placed on a
		timeline of activities sent up to the spacecraft up to twice a day during operations.

		&lt;br&gt;&lt;br&gt;
		&lt;a href="//www.cosmos.esa.int/web/esdc/esasky-observations#JWST"
		target="_blank"&gt;
		More information
		&lt;/a&gt; </text>

		<text key="resultsPresenter_helpDescription_observations_JWST_Mid-IR">
		The James Webb Space Telescope (JWST) is the largest optical or infrared observatory ever launched to space.
		Developed in a collaboration between NASA, ESA, and CSA, Webb observes the Universe in infrared light from its orbit at the Lagrangian point L2, 1.5 million km away from Earth.
		&lt;br&gt;&lt;br&gt;
		Following launch, and after an initial commissioning phase of 6 months, the observatory has entered its regular science operations phase,
		during which approved observation programs will be performed. Scientific data is collected from a set of observer-created programs placed on a
		timeline of activities sent up to the spacecraft up to twice a day during operations.

		&lt;br&gt;&lt;br&gt;
		&lt;a href="//www.cosmos.esa.int/web/esdc/esasky-observations#JWST"
		target="_blank"&gt;
		More information
		&lt;/a&gt; </text>

		<text key="resultsPresenter_helpDescription_spectra_JWST_Near-IR">
		The James Webb Space Telescope (JWST) is the largest optical or infrared observatory ever launched to space.
		Developed in a collaboration between NASA, ESA, and CSA, Webb observes the Universe in infrared light from its orbit at the Lagrangian point L2, 1.5 million km away from Earth.
		&lt;br&gt;&lt;br&gt;
		Following launch, and after an initial commissioning phase of 6 months, the observatory has entered its regular science operations phase,
		during which approved observation programs will be performed. Scientific data is collected from a set of observer-created programs placed on a
		timeline of activities sent up to the spacecraft up to twice a day during operations.

		&lt;br&gt;&lt;br&gt;
		&lt;a href="//www.cosmos.esa.int/web/esdc/esasky-observations#JWST"
		target="_blank"&gt;
		More information
		&lt;/a&gt; </text>

		<text key="resultsPresenter_helpDescription_spectra_JWST_Mid-IR">
		The James Webb Space Telescope (JWST) is the largest optical or infrared observatory ever launched to space.
		Developed in a collaboration between NASA, ESA, and CSA, Webb observes the Universe in infrared light from its orbit at the Lagrangian point L2, 1.5 million km away from Earth.
		&lt;br&gt;&lt;br&gt;
		Following launch, and after an initial commissioning phase of 6 months, the observatory has entered its regular science operations phase,
		during which approved observation programs will be performed. Scientific data is collected from a set of observer-created programs placed on a
		timeline of activities sent up to the spacecraft up to twice a day during operations.

		&lt;br&gt;&lt;br&gt;
		&lt;a href="//www.cosmos.esa.int/web/esdc/esasky-observations#JWST"
		target="_blank"&gt;
		More information
		&lt;/a&gt; </text>

	<text key="resultsPresenter_helpDescription_observations_Herschel">
		The available Herschel data include all public observations from
		the HIFI, PACS and SPIRE instruments (including PACS/SPIRE parallel
		observations).
		The downloadable scientific data are Standalone Browse Products.
		A brief description of these products is given below.
		Click
		&lt;a href="//www.cosmos.esa.int/web/herschel/data-products-overview"
		target="_blank"&gt;
		here
		&lt;/a&gt;
		for more information on the Herschel data products.

		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-observations#HERSCHEL-OBS"
		target="_blank"&gt;
		More information
		&lt;/a&gt; </text>
	<text key="resultsPresenter_helpDescription_observations_ISO-IR">
		The Infrared Space Observatory (ISO) was the world's
		first true orbiting infrared observatory launched in November 1995. It
		carried four scientific instruments: two spectrometers (SWS and LWS),
		an imaging photo-polarimeter (ISOPHOT) and a camera (ISOCAM). The only
		ISO imaging data provided through the ESASky interface are those from
		ISOCAM. Spectroscopic data from all four instruments are provided.

		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-observations#ISO-OBS"
		target="_blank"&gt;
		More information
		&lt;/a&gt; </text>

	<text key="resultsPresenter_helpDescription_observations_ALMA">
		ALMA (Atacama Large Millimeter/submillimeter Array) is the world's largest 
		ground-based facility for observations in the millimeter/submillimeter regime. 
		ALMA comprises a giant array of fifty 12-m antennas, which can be configured 
		to achieve baselines up to 16 km. It is equipped with state-of-the-art 
		receivers that cover all the atmospheric windows up to 1 THz.

		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-observations#ALMA-OBS"
		target="_blank"&gt;
		More information
		&lt;/a&gt; </text>

	<text key="resultsPresenter_helpDescription_catalogues_INTEGRAL">
		The IBIS/ISGRI Soft Gamma-Ray Source Catalog is an all-sky catalog
		based on INTEGRAL-IBIS observations performed during the first 1000
		orbits of the satellite. The catalogue was released in 2009 and
		updated in 2016. It is constructed from all public good-quality data
		available from the mission launch in 2002 up to the end of 2010, and
		it includes 939 sources significantly detected in the 17-100 keV
		energy band, of which 120 are previously undiscovered soft gamma-ray
		emitters.
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-catalogues#INTEGRAL"
		target="_blank"&gt;
		More information
		&lt;/a&gt; </text>
	<text key="resultsPresenter_helpDescription_catalogues_CHANDRA-SC2">
                The Chandra Source Catalog (CSC) is the definitive catalog of X-ray sources 
		detected by the Chandra X-ray Observatory. Version 2.0 (CSC 2.0) is the second 
		major release of the catalog, and represents a significant improvement with 
		respect to version 1.1 in terms of sky coverage, sensitivity and capabilities. 
		CSC 2.0 includes measured properties for 317,167 unique compact and extended 
		X-ray sources in the sky, allowing statistical analysis of large samples, as 
		well as individual source studies. Extracted properties are provided for 928,280 
		individual observation detections identified in 10,382 Chandra ACIS and HRC-I 
		imaging observations released publicly through the end of 2014.

		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-catalogues#Chandra"
		target="_blank"&gt;
		More information
		&lt;/a&gt; </text>
	<text key="resultsPresenter_helpDescription_catalogues_CHANDRA-SC21">
		The Chandra Source Catalog (CSC) is the definitive catalog of X-ray sources detected by the Chandra X-ray Observatory.