<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE internationalization [
	<!ELEMENT text (#PCDATA)>
	<!ATTLIST text key ID #REQUIRED>
]>
<Internationalization langCode="zh" label="中文">
	<text key="header_learnMore">
		了解更多关于ESASky的信息
	</text>
	<text key="header_getURLCurrentView">
		分享当前视图的网址
	</text>
	<text key="header_viewInWWTAbbr">
		WWT视图
    </text>
	<text key="header_viewInWWTFull">
		在万维望远镜中显示当前视图
    </text>
	<text key="header_takeScreenshotFull">
		获取当前页面截屏
	</text>
	<text key="header_takeScreenshot">
		截屏
	</text>
	<!-- menuPanel -->
	<text key="header_videoTutorials">
		视频教程
	</text>
	<text key="header_comunity">
		反馈
	</text>
	<text key="header_aboutUs">
		关于我们
	</text>
	<text key="header_releaseNotes">
		版本说明
	</text>
	<text key="header_newsletter">
		新闻简报
	</text>
	<text key="header_sciMode">
		科学模式
	</text>
	<text key="header_sciModeSwitchTooltip">
		在科学模式和探索模式之间切换
	</text>
	<text key="header_share">
		分享
	</text>
	<text key="header_help">
		帮助
	</text>

	<!-- SSOOrbitMetadataCallback -->
	<text key="SSOOrbitMetadataCallback_retrievingOrbitPoints">
		获取 $SSONAME$ 的轨迹点
	</text>

	<!-- countRequestCallback -->
	<text key="CountRequestCallback_countingAvailableData">
		数据刷新中……
	</text>

	<!-- publicationsSourcesCallback -->
	<text key="PublicationsSourcesCallback_retrievingPubSources">
		获取与文章相关的资源
	</text>

	<!-- publicationsBySourceCallback -->
	<text key="PublicationsBySourceCallback_retrievingPubsOf">
		检索与 $NAME$ 相关的文章
	</text>
	<text key="PublicationsBySourceCallback_helpTitle">
		文章
	</text>
	<text key="resultsPresenter_helpDescription_publications_ADS-PUB">
		SIMBAD天文数据库中与目标相关联的文章，或访问每篇文章所包含的目标。
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-interface#publications"
		target="_blank"&gt;
		关于此功能的完整文档
		&lt;/a&gt; 
	</text>

	<text key="tabulator_retrievingMissionData">
		获取 $NAME$ 数据
	</text>
	<text key="MetadataCallback_retrievingSSOMetadata">
		获取太阳系天体 $NAME$ 元数据
	</text>

	<!-- searchPanel -->
	<text key="searchPanel_inputByTargetName">
		输入目标名称：
	</text>
	<text key="searchPanel_solarSystemObjects">
		太阳系天体：
	</text>
	<text key="searchPanel_inputByName">
		按名称：
	</text>
	<text key="searchPanel_inputByObjectNumber">
		按天体编号：
	</text>
	<text key="searchPanel_inputByCoordinates">
		输入目标坐标：
	</text>
	<text key="searchPanel_wrongCoordsInput">
		坐标解析错误，请检查可用的输入格式
	</text>
	<text key="searchPanel_ssoTargetNotFound">
		未找到太阳系天体
	</text>
	<text key="searchPanel_seeMoreExamples">
		浏览更多示例
	</text>
	<text key="searchPanel_search">
		搜索...
	</text>

	<!-- searchPresenter_resolvingTarget -->
	<text key="searchPresenter_resolvingTarget">
		正在解析 $NAME$ ...
	</text>

	<!-- uploadTargetList -->
	<text key="uploadTargetList_targetList">
		目标列表文件：
	</text>
	<text key="uploadTargetList_targetListDescriptionText">
		选择一个示例目标列表或选择一个包含目标列表的文本文件，可以是目标名称（应能通过SIMBAD进行解析）或坐标列表。
		当列表加载时，界面顶部会出现“正在解析目标列表...”。当加载完成后，目标列表就会出现在左侧。
		&lt;br&gt;&lt;br&gt;
		点击一个目标以查看它。如果一个目标不能被SIMBAD天文数据库解析，它将会被排除掉。
		目标列表下方有一些视频风格的按钮，按下播放键后将对目标列表进行播放。
		当前目标将在列表中高亮显示，文本和注释也可以添加到目标列表中，其中文本会在ESASky的播放器按钮栏下方显示。
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-target-lists"
		target="_blank"&gt;
		文本显示的格式及一些示例文件，请参阅此链接
		&lt;/a&gt;
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-interface#list"
		target="_blank"&gt;
		关于此功能的完整文档
		&lt;/a&gt;
	</text>
	<text key="uploadTargetList_uploadTargetList">
		上传目标列表
	</text>
	<text key="uploadTargetList_uploadTargetListFailed">
		操作失败，由于
	</text>
	<text key="uploadTargetList_removeTargetList">
		移除目标列表
	</text>
	<text key="uploadTargetList_title">
		目标列表
	</text>
	<text key="uploadTargetList_selectList">
		选择目标列表
	</text>
	<text key="uploadTargetList_orUpload">
		或
	</text>
	<text key="uploadTargetList_resolvingTargetList">
		解析目标列表
	</text>

	<!-- uploadTargetListPanel -->
	<text key="uploadTargetListPanel_MultiTargetCatalog">
		多目标星表
	</text>

	<!-- treeMap -->
	<text key="treeMap_ASTRO_IMAGING">
		图像观测
	</text>
	<text key="treeMap_ASTRO_CATALOGUE">
		星表
	</text>
	<text key="treeMap_SSO">
		太阳系天体观测
	</text>
	<text key="treeMap_loading_ASTRO_IMAGING">
		加载观测结果
	</text>
	<text key="treeMap_loading_ASTRO_CATALOGUE">
		加载星表
	</text>
	<text key="treeMap_loading_SSO">
		加载太阳系天体
	</text>
	<text key="treeMap_noData_ASTRO_IMAGING">
		未找到图像观测结果
	</text>
	<text key="treeMap_noData_ASTRO_CATALOGUE">
		未找到星表条目
	</text>
	<text key="treeMap_noData_SSO">
		未找到太阳系天体观测结果
	</text>
	<text key="treeMap_nameOfSelectedLabel">
		太阳系天体：$SSONAME$ ($SSOTYPE$)
	</text>

	<!-- Sky -->
	<text key="sky_wavelength">
		波长
	</text>
	<text key="sky_selectWavelength">
		选择波段
	</text>
	<text key="sky_skies">
		天空图层
	</text>
	<text key="sky_selectSky">
		选择天空图层
	</text>
	<text key="sky_selectSky_help">
		天空按照不同波段（从伽马射线到射电波段）划分成了不同图层。
		底部的其他区块目前用于放置物理模型。
		在第一个面板中按波段选择天空图层，然后可在第二个面板中进行浏览。
		单击 i 图标可以找到天空图层的详细信息。
		想获取更多细节和所有可用的天空图层列表，可访问 HiPS 信息页。
		&lt;br&gt;&lt;br&gt;
		天空图层的颜色是可以修改的，可以选择颜色表中的“原色”、“EOSB”、“普朗克”、“彩虹”、“灰度”和“立方螺旋”。
		&lt;br&gt;&lt;br&gt;
		可以通过 + 按钮添加一个天空图层。
		&lt;br&gt;&lt;br&gt;
		单击视频样式的按钮可以在堆栈中控制播放内容“前进”、“后退”或“停止”。
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-interface#skies"
		target="_blank"&gt;
		关于此功能的完整文档
		&lt;/a&gt; 
	</text>
	<text key="sky_selectASky">
		选择一个天空图层
	</text>
	<text key="sky_skyDetails">
		天空图层细节
	</text>
	<text key="sky_removeSky">
		移除天空图层
	</text>
	<text key="sky_loadingSkies">
		加载天空图层
	</text>

	<!-- HiPS Details Popup -->
	<text key="hiPSDetailsPopup_mapName">
		星图名称：
	</text>
	<text key="hiPSDetailsPopup_mission">
		任务：
	</text>
	<text key="hiPSDetailsPopup_instrument">
		仪器：
	</text>
	<text key="hiPSDetailsPopup_wavFreq">
		波长/频率：
	</text>
	<text key="hiPSDetailsPopup_mapCreatedBy">
		星图创建者：
	</text>
	<text key="hiPSDetailsPopup_forMoreInformation">
		更多信息请点击&amp;nbsp;
	</text>
	<text key="instrumentDetailsPopup_forMoreInformation">
		更多信息请点击&amp;nbsp;
	</text>
	<text key="hiPSDetailsPopup_here">
		此处
	</text>
	<text key="hiPSDetailsPopup_close">
		关闭
	</text>

	<!-- Change Palette Button -->
	<text key="changePaletteBtn_changePaletteTooltip">
		调色板
	</text>

	<text key="tabulator_download">
		下载行
	</text>

	<text key="dateFilter_resetFilter">
		重置过滤条件
	</text>
	<text key="rangeFilter_resetFilter">
		重置过滤条件
	</text>

	<!-- commonObservationTablePanel -->
	<text key="tabulator_sendRowToVOA">
		发送数据行到虚拟天文台应用程序
	</text>

	<!-- planObservationPanel -->
	<text key="planObservationPanel_projectFutureObservations">
		$MISSION$观测规划工具
	</text>
	<text key="planObservationPanel_helpMessageText">
		此工具将天文仪器的覆盖区域显示到天空中，并且可以任意选择位置和方向，以协助天文学家制定观测计划。
		目前，该工具可应用于詹姆斯韦伯天文望远镜（JWST）的所有仪器，包括它的整个焦平面。在不久的将来，还有将适配其他望远镜，如XMM牛顿望远镜、哈勃空间望远镜等等。
		&lt;br&gt;&lt;br&gt;
		注意：此功能不是为了取代詹姆斯韦伯天文望远镜的观测提案工具（APT），而是用于协助那些准备使用詹姆斯韦伯天文望远镜对ESASky中已有数据进行重复观测的天文学家。
		或者协助天文学家确认他们的观测点覆盖（或避开）了特定区域。
		利用这个功能生成的坐标和位置角度应在官方的APT中进行检查和不断完善。
		关于APT的安装及相关信息，请查看
		&lt;a href="//www.stsci.edu/hst/proposing/apt" target="_blank"&gt;
		这个 STScI 网页&lt;/a&gt;; 
		关于JWST不同仪器的详细信息，
		&lt;a href="//stsci.edu/jwst/instrumentation" target="_blank"&gt;
		可以在这里查阅&lt;/a&gt;。
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.youtube.com/watch?v=n2iW1HfVgVE&amp;feature=youtu.be"
		target="_blank"&gt;
		也可以访问如下视频：了解如何制订JWST的观测计划&lt;/a&gt;。
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-interface#planning"
		target="_blank"&gt;
		关于此功能的完整文档&lt;/a&gt; 		
	</text>

	<!-- futureFootprintRow -->
	<text key="futureFootprintRow_addJWSTInstrument">
		添加JWST的一个终端设备
	</text>
	<text key="futureFootprintRow_instrAngleInfo">
		&lt;a href="//jwst-docs.stsci.edu/jwst-observatory-characteristics/jwst-position-angles-ranges-and-offsets" target="_blank"&gt;更多信息请点击“这里处&lt;/a&gt;
	</text>
	<text key="futureFootprintRow_instrAngle">
		仪器在焦面上的转角：
	</text>
	<text key="futureFootprintRow_offsetAngle">
		偏移角度:
	</text>
	<text key="futureFootprintRow_totalRotation">
		焦面在天空上的转角
	</text>
	<text key="futureFootprintRow_tooltip">
		JWST角度详情
	</text>
	<text key="futureFootprintRow_rotation">
		旋转
	</text>
	<text key="futureFootprintRow_allInstruments">
		所有仪器
	</text>
	<text key="futureFootprintRow_removeFootprint">
		移除该覆盖图
	</text>
	<text key="futureFootprintRow_increase">
		增强
	</text>
	<text key="futureFootprintRow_angleBy">
		角度
	</text>
	<text key="futureFootprintRow_decrease">
		减弱
	</text>
	<text key="futureFootprintRow_copyCoordinatesAndData">
		复制坐标和数据
	</text>
	<text key="futureFootprintRow_centre">
		中心
	</text>
	<text key="futureFootprintRow_coordinateSystem">
		坐标系：
	</text>
	<text key="futureFootprintRow_dataCopiedToClipboard">
		数据已复制到剪贴板
	</text>
	<text key="futureFootprintRow_aperture">
		光圈
	</text>


	<!-- screenShotDialogBox -->
	<text key="screenShotDialogBox_screenshot">
		ESASky截屏
	</text>

	<!-- ctrlToolBar -->
	<text key="ctrlToolBar_URLClipboard">
		网址已复制到剪贴板
	</text>

	<!-- ctrlToolBarPresenter -->
	<text key="ctrlToolBarPresenter_bibcode">
		期刊文章识别码：$HTML$
	</text>
	<text key="ctrlToolBarPresenter_authors">
		作者：$HTML$
	</text>
	<text key="ctrlToolBarPresenter_journal">
		期刊：$JOURNAL$, $DATE$
	</text>
	<text key="ctrlToolBarPresenter_pubSources">
		文章包含的源：
	</text>
	<text key="ctrlToolBarPresenter_adsSearch">
		检索ADS：$HTML$
	</text>
	<text key="ctrlToolBarPresenter_authorSources">
		与作者相关的源：
	</text>
	<text key="ctrlToolBarPresenter_showingMaxSources">
		只显示前 $COUNT$ 个源
	</text>
	<text key="ctrlToolBarPresenter_showingCountSources">
		显示 $COUNT$ 个源
	</text>
	<text key="ctrlToolBarPresenter_loadPublicationDetails">
		加载文章的详细信息
	</text>
	<text key="ctrlToolBarPresenter_retrievingPublicationTargetList">
		获取目标列表
	</text>

	<!-- playerPanel -->
	<text key="playerPanel_next">
		下一层
	</text>
	<text key="playerPanel_pause">
		暂停
	</text>
	<text key="playerPanel_play">
		自动切换
	</text>
	<text key="playerPanel_previous">
		上一层
	</text>
	<text key="playerPanel_surveyTourStarted">
		巡天漫游开始
	</text>

	<!-- sampConstants -->
	<text key="sampConstants_help">
		关于SAMP互操作信息的帮助
	</text>
	<text key="sampConstants_sendingViaSamp">
		通过SAMP发送 @@
	</text>

	<!-- webConstants -->
	<text key="webConstants_manageSkies">
		天空图层
	</text>
	<text key="webConstants_uploadTargetList">
		目标列表
	</text>
	<text key="webConstants_exploreImageObservations">
		图像数据
	</text>
	<text key="webConstants_exploreCatalogue">
		星表数据
	</text>
	<text key="webConstants_exploreData">
		浏览 $TARGET$ 的数据
	</text>
	<text key="webConstants_trackSSO">
		通过搜索框追踪太阳系天体
	</text>
	<text key="webConstants_projectFutureObservations">
		观测规划工具
	</text>
	<text key="webConstants_explorePublications">
		文献数据
	</text>
	<text key="webConstants_exploreRandomTarget">
		随机浏览
	</text>

	<!-- displayUtils -->
	<text key="displayUtils_connectivityProblems">
		网络连通问题
	</text>
	<text key="displayUtils_VOnotFound">
		未能在您的电脑上找到正在运行的虚拟天文台工具
	</text>
	<text key="displayUtils_startOneOf">
		请选择一项：
	</text>
	<text key="displayUtils_toCommunicateWithDS9">
		为了与DS9通信，您也必须启动
	</text>
	<text key="displayUtils_seeHelp">
		了解更多细节请查看帮助
	</text>
	<text key="displayUtils_tryAgain">
		当这些程序运行之后，请再次尝试。
	</text>

	<!-- resultsPresenter -->
	<text key="resultsPresenter_computingDataCrossMatch">
		与 $SSOTEXT$ 进行交叉证认
	</text>
	<text key="resultsPresenter_helpDescription_observations_INTEGRAL">
		INTEGRAL/IBIS卫星的观测结果包含了目标位置周围大量的单次曝光(科学窗口)。
		由于这个原因，加之IBIS视场非常大，使得其难以显示其所有科学窗口的天区覆盖情况。
		因而ESASky只显示其每次观测所指向的中心位置，并列出所有覆盖了该位置的科学窗口。
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-observations#INTEGRAL"
		target="_blank"&gt;
		更多信息
		&lt;/a&gt; 
	</text>
	<text key="resultsPresenter_helpDescription_observations_XMM">
		XMM牛顿望远镜(XMM-Newton)观测数据中包含出现在XMM-Newton归档数据(&lt;a href="//nxsa.esac.esa.int/nxsa-web/#home"
		target="_blank"&gt;XSA&lt;/a&gt;)中已公开的高级处理管道系统(PPS)数据产品。
		所包含的数据结合了三个摄像机（EPIC PN、EPIC MOS1和EPIC MOS2）在0.2-12 keV能量范围的高级图像产品。
		数据的选择标准建立于已存在且公开的EPIC图像组合。
		拼接子产品被排除在外，但观测结果的整体拼接图像是包含其中的。

		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-observations#XMM-Newton-OBS"
		target="_blank"&gt;
		更多信息
		&lt;/a&gt;
	</text>
	<text key="resultsPresenter_helpDescription_observations_Chandra">
		钱德拉(Chandra)数据集包括Chandra数据中心提供的来自ACIS、LETG、HETG和HRC仪器的全部公开观测结果(图像和光谱)，并会持续更新
		(&lt;a href="//cda.harvard.edu/chaser/"
		target="_blank"&gt;cda.harvard.edu/chaser/&lt;/a&gt;)。
		有关 Chandra 及其数据产品的详细资料，请浏览以下网址:
		&lt;a href="//cxc.harvard.edu/" target="_blank"&gt;
		cxc.harvard.edu/&lt;/a&gt;.
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-observations#Chandra-OBS"
		target="_blank"&gt;
		更多信息
		&lt;/a&gt;
	</text>
	<text key="resultsPresenter_helpDescription_observations_SUZAKU">
		这些观测结果包括了出现在日本ISAS数据记录传输系统(DARTS)中的朱雀号探测器(SUZAKU)的所有公开图像产品。
		有关SUZAKU任务及其数据产品可访问
		&lt;a href="//www.darts.isas.jaxa.jp/astro/suzaku/" target="_blank"&gt;
		www.darts.isas.jaxa.jp/astro/suzaku/&lt;/a&gt;。
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-observations#SUZAKU-OBS"
		target="_blank"&gt;
		更多信息
		&lt;/a&gt;
	</text>
	<text key="resultsPresenter_helpDescription_observations_XMM-OM-OPTICAL">
		ESASky中的&lt;a href="//www.cosmos.esa.int/web/xmm-newton/technical-details-om"
		target="_blank"&gt;
		光学监视器(OM)
		&lt;/a&gt;数据基于开放的观测数据，其中至少有一个OM高级图像流水线产品。
		在流水线中，各个OM滤镜图像被组合起来并向北对齐。
		ESASky中包含了以下OM图像文件类型: RSIMAG默认模式(RSIMAG), 全帧低分辨率模式(LSIMAG), 全帧高分辨率模式(HSIMAG), 和用户定义模式(USIMAG)。
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-observations#OM-OBS"
		target="_blank"&gt;
		更多信息
		&lt;/a&gt; 
	</text>
	<text key="resultsPresenter_helpDescription_observations_XMM-OM-UV">
		ESASky中的
		&lt;a href="//www.cosmos.esa.int/web/xmm-newton/technical-details-om"
		target="_blank"&gt;
		光学监视器(OM)
		&lt;/a&gt;
		数据基于开放的观测数据，其中至少有一个OM高级图像流水线产品。
		在流水线中，各个OM滤镜图像被组合起来并向北对齐。
		ESASky中包含了以下OM图像文件类型: RSIMAG默认模式(RSIMAG), 全帧低分辨率模式(LSIMAG), 全帧高分辨率模式(HSIMAG), 和用户定义模式(USIMAG)。
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-observations#OM-OBS"
		target="_blank"&gt;
		更多信息
		&lt;/a&gt;
	</text>
	<text key="resultsPresenter_helpDescription_observations_ISO-IR">
		1995年11月发射的红外空间天文台(ISO)是世界上第一个真正的在轨红外天文台。
		它携带了四种科学仪器:两台光谱仪(SWS和LWS)、一台成像光偏振仪(ISOPHOT)和一台照相机(ISOCAM)。
		ESASky仅能提供来自于ISOCAM的ISO图像数据，而来自全部四台仪器的光谱数据则均能提供。

		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-observations#ISO-OBS"
		target="_blank"&gt;
		更多信息
		&lt;/a&gt; 
	</text>
	<text key="resultsPresenter_helpDescription_catalogues_INTEGRAL">
		IBIS/ISGRI软伽玛射线源星表是一个全天星表，基于INTERGRAL-IBIS卫星的前1000轨数据。
		该星表于2009年发布，并于2016年进行了更新。
		它由卫星任务在2002年至2010年末期间所有高质量的公开数据构建而成，
		包含了在17-100 keV能量范围可以明显检测到的939个源，
		其中有120个是之前所未发现的软伽马射线发射体。
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-catalogues#INTEGRAL"
		target="_blank"&gt;
		更多信息
		&lt;/a&gt; 
	</text>
	<text key="resultsPresenter_helpDescription_catalogues_XMM-EPIC">
		4XMM-DR12星表包含了由XMM牛顿望远镜12,712次PIC观测中的源，覆盖从0.2 keV到12 keV的能量范围。
		目前，ESASky中只显示质量标志(QUALITY flag)为0或1的源(即“好”或“有可疑参数”的源)。

		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="https://www.cosmos.esa.int/web/esdc/esasky-catalogues#4XMM"
		target="_blank"&gt;
		更多信息
		&lt;/a&gt;
	</text>
	<text key="resultsPresenter_helpDescription_catalogues_XMM-OM">
		SUSS5.0 星表集合了XMM-Newton太空望远镜所搭载的光学监视器偶然观测到的目标。
		它提供了超过590万个源的位置、星等，及其在六个宽域紫外、光学滤镜的流量，还包括了其诊断报告和变量统计。

		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-catalogues#SUSS"
		target="_blank"&gt;
		更多信息
		&lt;/a&gt;
	</text>
	<text key="resultsPresenter_helpDescription_catalogues_Tycho-2">
		Tycho-2星表是一个天体测量参考星表，包含了天空中250万颗最亮恒星的位置、自行和二色测光(B和V波段)数据。该星表基于依巴谷卫星星图仪的观测，创建所用观测数据与原始第谷星表相同。使用改进的处理技术，光谱条数明显增多，精度显著提高。
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-catalogues#TYCHO"
		target="_blank"&gt;
		更多信息
		&lt;/a&gt; 
	</text>

	<text key="resultsPresenter_helpDescription_catalogues_TwoMASS">
		2微米全天巡视(2MASS)观测在三个近红外波段（J、H、Ks）覆盖了99.998%的星空。2MASS点源星表(PSC)包含470,992,970个点源的位置和测光信息。该星表中的源至少在一个波段的观测数据信噪比大于7，或三个波段的信噪比都大于5。此外，源的位置也必须满足一些条件，以确保它不是伪信号或存在源之间互相干扰。
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-catalogues#2MASS"
		target="_blank"&gt;
		更多信息
		&lt;/a&gt; 
	</text>
	<text key="resultsPresenter_helpDescription_catalogues_AllWise">
		AllWISE源星表包含了AllWISE多波段星图中747,634,026个天体的天体测量信息，以及四个波段(3.4微米、4.6微米、12微米和22微米)的中红外测光信息。相对WISE星表，AllWISE星表改进了全部四个波段离散光源的测光信息。此外，该星表还改进了每颗星变源概率的值。同时，由于在两次巡天观测相隔的11年间，2MASS参考星表的自行修正，天体测量信息得以改进。
	&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-catalogues#WISE"
		target="_blank"&gt;
		更多信息
		&lt;/a&gt; 
	</text>
	<text key="resultsPresenter_helpDescription_catalogues_Hipparcos-2">
		Hipparcos-2星表是对依巴谷观测任务获得数据的更新。它将Hp星等小于等于8的恒星的精度提高了4倍。它包含了118,218颗恒星的位置、视差和自行数据。
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-catalogues#HIPPARCOS"
		target="_blank"&gt;
		更多信息
		&lt;/a&gt; 
	</text>
	<text key="resultsPresenter_helpDescription_catalogues_Herschel-HPPSC-070">
		赫歇尔-帕克斯点源星表(HPPSC)包含大约50万个条目。数据来自赫歇尔望远镜搭载的光电阵列相机和光谱仪（PACS）可观测的三个波段，覆盖约8%的远红外星空。
		宽带滤波器集中在70微米、100微米和160微米，角分辨率分别为5.6"、6.8"和11.3"。这个星表由三张表格组成，每个波段对应一个星表。
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-catalogues#HPPSC"
		target="_blank"&gt;
		More information
		&lt;/a&gt; 
	</text>
	<text key="resultsPresenter_helpDescription_catalogues_Herschel-HPPSC-100">
		赫歇尔-帕克斯点源星表(HPPSC)包含大约50万个条目。数据来自赫歇尔望远镜搭载的光电阵列相机和光谱仪（PACS）可观测的三个波段，覆盖约8%的远红外星空。
		宽带滤波器集中在70微米、100微米和160微米，角分辨率分别为5.6"、6.8"和11.3"。这个星表由三张表格组成，每个波段对应一个星表。 
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-catalogues#HPPSC"
		target="_blank"&gt;
		更多信息
		&lt;/a&gt;
	</text>
	<text	key="resultsPresenter_helpDescription_catalogues_Herschel-HPPSC-160">
		赫歇尔-帕克斯点源星表(HPPSC)包含大约50万个条目。数据来自赫歇尔望远镜搭载的光电阵列相机和光谱仪（PACS）可观测的三个波段，覆盖约8%的远红外星空。
		宽带滤波器集中在70微米、100微米和160微米，角分辨率分别为5.6"、6.8"和11.3"。这个星表由三张表格组成，每个波段对应一个星表。 
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-catalogues#HPPSC"
		target="_blank"&gt;
		更多信息
		&lt;/a&gt; 
	</text>
	<text key="resultsPresenter_helpDescription_catalogues_Herschel-SPSC-250">
		SPIRE点源星表(SPSC)有超过160万个条目，由赫歇尔望远镜上搭载的光谱及测光成象接收机(SPIRE)在亚毫米范围内所进行的6878次观测中提取出来。该星表由三个表格组成，每个表格对应SPIRE的一个测光波段：250微米、350微米和500微米(分别对应1199千兆赫、857千兆赫和600千兆赫)。
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-catalogues#HSPSC"
		target="_blank"&gt;
		更多信息
		&lt;/a&gt; 
	</text>
	<text key="resultsPresenter_helpDescription_catalogues_Herschel-SPSC-350">
		SPIRE点源星表(SPSC)有超过160万个条目，由赫歇尔望远镜上搭载的光谱及测光成象接收机(SPIRE)在亚毫米范围内所进行的6878次观测中提取出来。该星表由三个表格组成，每个表格对应SPIRE的一个测光波段：250微米、350微米和500微米(分别对应1199千兆赫、857千兆赫和600千兆赫)。
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-catalogues#HSPSC"
		target="_blank"&gt;
		更多信息
		&lt;/a&gt; 
	</text>
	<text key="resultsPresenter_helpDescription_catalogues_Herschel-SPSC-500">
		SPIRE点源星表(SPSC)有超过160万个条目，由赫歇尔望远镜上搭载的光谱及测光成象接收机(SPIRE)在亚毫米范围内所进行的6878次观测中提取出来。该星表由三个表格组成，每个表格对应SPIRE的一个测光波段：250微米、350微米和500微米(分别对应1199千兆赫、857千兆赫和600千兆赫)。
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-catalogues#HSPSC"
		target="_blank"&gt;
		更多信息
		&lt;/a&gt; 
	</text>
	<text key="resultsPresenter_helpDescription_catalogues_Planck-PGCC">
		PGCC2包含13，188个银河系内的源和54个麦哲伦星云内的源，都在普朗克数据中被定义为冷源(低于周围环境温度的源)。这些源都是从普朗克HFI 857、545和353 GHz图和3 THz IRIS图中筛选出来的。观测标准为在所有普朗克波段的信噪比大于4，并且与其他源的最小角距离为5角分。
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-catalogues#PGCC"
		target="_blank"&gt;
		更多信息
		&lt;/a&gt; 
	</text>
	<text key="resultsPresenter_helpDescription_catalogues_Planck-PCCS2E-HFI">
		PCCS2是从普朗克全任务强度和偏振图中提取的一组单频源星表。这些星图包含了LFI通道48个月的数据，以及HFI通道29个月的数据。因此，从这些图中得到的流量密度，是这两个时间段内，源发射的平均值。对于100-353兆赫兹通道，星表中还包含了有显著偏振（>99.99%）的源的偏振流量密度磁通密度和偏振角。
		&lt;br&gt;
		100兆赫兹及以上源的星表被分成了两个次星表：PCCS2，包括所有可靠观测(>80%)；PCCS2E，包含位于无法估计其可靠性天区的源。
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-catalogues#PCCS2"
		target="_blank"&gt;
		更多信息
		&lt;/a&gt; 
	</text>
	<text key="resultsPresenter_helpDescription_catalogues_Planck-PCCS2-HFI">
		PCCS2是从普朗克全任务强度和偏振图中提取的一组单频源星表。这些星图包含了LFI通道48个月的数据，以及HFI通道29个月的数据。因此，从这些图中得到的流量密度，是这两个时间段内，源发射的平均值。对于100-353兆赫兹通道，星表中还包含了有显著偏振（>99.99%）的源的偏振流量密度磁通密度和偏振角。
		&lt;br&gt;
		100兆赫兹及以上源的星表被分成了两个次星表：PCCS2，包括所有可靠观测(>80%)；PCCS2E，包含位于无法估计其可靠性天区的源。
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-catalogues#PCCS2"
		target="_blank"&gt;
		更多信息
		&lt;/a&gt;
	</text>
	<text key="resultsPresenter_helpDescription_catalogues_Planck-PCCS2-LFI">
		PCCS2是从普朗克全任务强度和偏振图中提取的一组单频源星表。这些星图包含了LFI通道48个月的数据，以及HFI通道29个月的数据。因此，从这些图中得到的流量密度，是这两个时间段内，源发射的平均值。对于100-353兆赫兹通道，星表中还包含了有显著偏振（>99.99%）的源的偏振流量密度磁通密度和偏振角。
	 	&lt;br&gt;&lt;br&gt;
		&lt;a href="//www.cosmos.esa.int/web/esdc/esasky-catalogues#PCCS2"
		target="_blank"&gt;
		更多信息
		&lt;/a&gt;
	</text>
	<text key="resultsPresenter_helpDescription_catalogues_Planck-PSZ2">
		普朗克SZ星表是从普朗克数据中提取出来的一个几乎覆盖全天的SZ探测表，源于HFI频率通道图，并使用PCCS星表中相应通道的亮点源（信噪比＞10）遮挡、填充生成。这个星表包含1653个探测数据，其中1203个经由外部数据对比确认为星团。
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-catalogues#PSZ2"
		target="_blank"&gt;
		更多信息
		&lt;/a&gt;
	</text>
	<text key="resultsPresenter_helpDescription_spectra_XMM-NEWTON">
		包括高级别数据处理流水线系统（PPS）产生数据在内的XMM牛顿望远镜的观测数据在XXM牛顿望远镜科学归档中已经开放。(&lt;a href="//nxsa.esac.esa.int/nxsa-web/#home" target="_blank"&gt;XSA&lt;/a&gt;). 
		RGS设备在5-35 ?[0.33-2.5 keV]（第一级光谱）获得高分辨本领（150-800）。对两个频谱仪，有效面积在15 ? [0.83 keV] (第一级)达到峰值，约为150平方厘米。
		&lt;br&gt;&lt;br&gt;
		&lt;a href="//www.cosmos.esa.int/web/esdc/esasky-observations#RGS"
		target="_blank"&gt;
		更多信息
		&lt;/a&gt;
	</text>
	<text key="resultsPresenter_helpDescription_spectra_Chandra">
		钱德拉数据集包括来自ACIS、LETG、HETG和HRC仪器所有截至2017年10月8日前公开的观测数据（图像和光谱），并且可通过(&lt;a href="//cda.harvard.edu/chaser/" target="_blank"&gt;cda.harvard.edu/chaser/&lt;/a&gt;)在钱德拉数据归档中查找。
		更多关于钱德拉任务的详细信息及其数据产品可访问：&lt;a href="//cxc.harvard.edu/" target="_blank"&gt; cxc.harvard.edu/&lt;/a&gt;
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-observations#Chandra-OBS"
		target="_blank"&gt;
		更多信息
		&lt;/a&gt;
	</text>
	<text key="resultsPresenter_helpDescription_spectra_IUE">
		国际紫外探测(IUE)是欧洲空间局、美国航天局和英国粒子物理学和天文学研究委员会（PPARC）的联合项目。
		该任务在1978年至1996年运行期间，使用了三种中阶梯光栅摄谱仪：单波长光谱仪(SWP)、低功率光谱仪(LWP)和低功率光谱仪(LWR)。
		在低分辨率模式下，光谱分辨率为~0.6 纳米, 对应R~250在150纳米和R~450在270纳米的分辨本领。在高分辨率模式下，分辨率为~0.02纳米,对应R~7500在150纳米和R~13500在270纳米的分辨本领。
		ESASky提供了直接从&lt;a href="//sdc.cab.inta-csic.es/ines/index2.html" target="_blank"&gt;IU新提取光谱(INES)归档 &lt;/a&gt;获得的三种摄谱仪的完全校准光谱。该归档存储于位于马德里（西班牙）附近的&lt;a href="//cab.inta-csic.es/en/" target="_blank"&gt;西班牙天体生物学中心（CAB）&lt;/a&gt; 
		&lt;br&gt;&lt;br&gt;
		&lt;a href="//www.cosmos.esa.int/web/esdc/esasky-observations#IUE"
		target="_blank"&gt;
		更多信息
		&lt;/a&gt; 
	</text>
	<text key="resultsPresenter_helpDescription_spectra_ISO-IR">
		红外空间天文台(ISO)是世界上第一个真正的轨道红外天文台，于1995年11月发射升空。它携带了四种科学设备：两台光谱仪(SWS和LWS)、一台成像光偏振仪(ISOPHOT)和一台照相机(ISOCAM)。可通过ESASky界面浏览的ISO图像数据只有来自ISOCAM的数据。四台仪器获得的光谱数据则可全部浏览。
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-observations#ISO-OBS"
		target="_blank"&gt;
		更多信息
		&lt;/a&gt; 
	</text>
	<text key="resultsPresenter_helpDescription_spectra_Herschel">
		可使用的赫歇尔（Herschel)数据包括了来自远红外外差光谱仪、光电探测器阵列照相机和光谱仪以及光谱和光度成像接收器三大设备的所有开放观测数据(包括PACS/SPIRE的平行观测)。
		这些可下载的科学数据是独立浏览产品。产品的简介:点击&lt;a href="//www.cosmos.esa.int/web/herschel/data-products-overview" target="_blank"&gt; 这里 &lt;/a&gt; 了解赫歇尔数据产品的更多信息。
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-observations#HERSCHEL-OBS"
		target="_blank"&gt;
		更多信息
		&lt;/a&gt; 
	</text>
	<text key="resultsPresenter_helpDescription_sso_Herschel">
		可使用的赫歇尔（Herschel)数据包括了来自远红外外差光谱仪、光电探测器阵列照相机和光谱仪以及光谱和光度成像接收器三大设备的所有开放观测数据(包括PACS/SPIRE的平行观测)。
		这些可下载的科学数据是独立浏览产品。产品的简介:点击&lt;a href="//www.cosmos.esa.int/web/herschel/data-products-overview" target="_blank"&gt; 这里 &lt;/a&gt; 了解赫歇尔数据产品的更多信息。
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-observations#HERSCHEL-OBS"
		target="_blank"&gt;
		更多信息
		&lt;/a&gt; 
	</text>
	<text key="resultsPresenter_helpDescription_sso_XMM">
		包括高级别数据处理流水线系统（PPS）产生数据在内的XMM牛顿望远镜的观测数据在XXM牛顿望远镜科学归档中已经开放。(&lt;a href="//nxsa.esac.esa.int/nxsa-web/#home" target="_blank"&gt;XSA&lt;/a&gt;). 
		关于XMM牛顿望远镜数据产品的详细信息可在&lt;a href="//www.cosmos.esa.int/web/xmm-newton/guide-to-xmm-products" target="_blank"&gt;XXM牛顿望远镜科学归档数据产品指南&lt;/a&gt;中查看。
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-observations#XMM-Newton-OBS"
		target="_blank"&gt;
		更多信息
		&lt;/a&gt; 
	</text>
	<!-- closeableTabLayoutPanel -->
	<text key="closeableTabLayoutPanel_closeTab">
		关闭标签
	</text>
	<text key="closeableTabLayoutPanel_sendTableToVOA">
		发送表格至虚拟天文台应用
	</text>
	<text key="closeableTabLayoutPanel_recentre">
		重新居中
	</text>
	<text key="closeableTabLayoutPanel_refreshData">
		刷新数据
	</text>
	<text key="closeableTabLayoutPanel_styleBtn">
		自定义类型
	</text>
	<text key="abstractTablePanel_filterTooltip">
		过滤器	
	</text>
	<!-- targetWidget -->
	<text key="targetWidget_showTargetInTheSky">
		在天空中显示目标
	</text>
	<text key="targetWidget_targetNotFoundInSimbad">
		在SIMBAD天文数据库中未找到目标
	</text>
	<!-- welcomeDialog -->
	<text key="WelcomeDialog_title">
		欢迎来到ESASky！
	</text>
	<text key="WelcomeDialog_checkbox">
		不再显示这个对话框	
	</text>
	<text key="WelcomeDialog_cookieInformation">
		（阅读我们的cookie政策）
	</text>
	<text key="WelcomeDialog_closeButton">
		关闭
	</text>
	<text key="WelcomeDialog_chooseMode">
		选择一个模式	
	</text>
	<text key="WelcomeDialog_modeDescription">
		选择科学模式探索并下载科研可用数据。
		&lt;br&gt;&lt;br&gt;
		选择探索模式简单地浏览不同波段星空。
		&lt;br&gt;&lt;br&gt;
		&lt;a
		href="//www.cosmos.esa.int/web/esdc/esasky-interface#MODES"
		target="_blank"&gt;
		更多信息
		&lt;/a&gt;
	</text>
	<text key="WelcomeDialog_modeDescriptionHeader">
		ESASky模式
	</text>
	<text key="WelcomeDialog_science">
		科学
	</text>
	<text key="WelcomeDialog_explorer">
		探索
	</text>
	<text key="AllSkyPanel_fovButton">
		以十进制模式增加视场
	</text>
	<!-- allSkyPresenter -->
	<text key="AllSkyPresenter_futureSelectedDetectorCatalog">
		选择的探测器星表
	</text>
	<!-- allSkyFocusPanel -->
	<text key="AllSkyFocusPanel_searchInSimbad">
		在SIMBAD中搜索坐标，半径2角秒
	</text>
	<text key="AllSkyFocusPanel_searchInNed">
		在NED中搜索坐标，半径2角秒
	</text>
	<text key="AllSkyFocusPanel_searchInVizierPhotometry">
		在VizieR测光显示器中显示测光信息，半径5角秒
	</text>
	<text key="AllSkyFocusPanel_searchInVizier">
		在VizieR中搜索星表，半径2角秒
	</text>
	<text key="AllSkyFocusPanel_searchIn">
		搜索
	</text>
	<!-- fovDialogBox -->
	<text key="FovDialogBox_inputFoVTextBox">
		以十进制模式增加视场
	</text>
	<text key="FovDialogBox_wrongFov">
		只可输入数字和点
	</text>
	<!-- zoomControlPanel -->
	<text key="ZoomControlPanel_zoomIn">
		放大
	</text>
	<text key="ZoomControlPanel_zoomOut">
		缩小
	</text>
	<!-- EsaSkyNumberControl -->
	<text key="EsaSkyNumberControl_increaseWithLabel">
		增加$TITLE$ $STEP$
	</text>
	<text key="EsaSkyNumberControl_decreaseWithLabel">
		减少$TITLE$ $STEP$
	</text>
	<!-- saveAllView -->
	<text key="saveAllView_save_In_VOTABLE_Format">
		VOTable
	</text>
	<text key="saveAllView_save_In_VOTABLE_Format_Title">
		保存为 XML VOTable
	</text>
	<text key="saveAllView_save_In_CSV_Format">
		CSV
	</text>
	<text key="saveAllView_save_In_CSV_Format_Title">
		保存为CSV，逗号分隔
	</text>
	<text key="saveAllView_Download_Btn_Text">
		下载数据产品
	</text>
	<text key="saveAllView_Download_Btn_Title">
		下载选择的产品
	</text>
	<text key="saveAllView_Rows_Selected_Label">
		当前选项卡中选中$COUNT$行
	</text>
	<!-- pointInformation -->
	<text key="PointInformation_to">
		从$FROM$到$TO$	
	</text>
	<!-- multiTargetTooltip -->
	<text key="MultiTargetTooltip_nearestSimbadId">
		最近的SIMBAD主ID
	</text>
	<!-- planningDetectorCenterTooltip -->
	<text key="PlanningDetectorCenterTooltip_instrument">
		设备：
	</text>
	<text key="PlanningDetectorCenterTooltip_detector">
		测器：
	</text>
	<text key="PlanningDetectorCenterTooltip_referenceRA">
		参考赤经
	</text>
	<text key="PlanningDetectorCenterTooltip_referenceDEC">
		参考赤纬
	</text>
	<text key="stylePanel_Title">
		$MISSION$类型
	</text>
	<text key="stylePanel_helpMessageText">
		使用这个面板自定义结果类型
	</text>
	<text key="stylePanel_removeAvgCheckBox">
		减去平均自行
	</text>
	<text key="stylePanel_removeMedianCheckBox">
		减去中位自行
	</text>
	<text key="sourceLimitNumImages">
		显示观测次数最多的$sourceLimit$源
	</text>
	<text key="SoftX-ray">
		软X射线
	</text>
	<text key="Soft&#032;X-ray">
		软X射线
	</text>
	<text key="HardX-ray">
		硬X射线
	</text>
	<text key="Hard&#032;X-ray">
		硬X射线
	</text>
	<text key="UV">
		紫外
	</text>
	<text key="Ultraviolet">
		紫外
	</text>
	<text key="Optical">
		光学
	</text>
	<text key="Near-IR">
		近红外
	</text>
	<text key="NearIR">
		近红外
	</text>
	<text key="MidToFarIR">
		中远红外
	</text>
	<text key="Mid-IR">
		中红外
	</text>
	<text key="MidIR">
		中红外
	</text>
	<text key="Mid-Infrared">
		中红外
	</text>
	<text key="MidInfrared">
		中红外
	</text>
	<text key="Far-IR">
		远红外
	</text>
	<text key="FarIR">
		远红外
	</text>
	<text key="Near-Infrared">
		近红外
	</text>
	<text key="NearInfrared">
		近红外
	</text>
	<text key="MidToFarInfrared">